name: Build Solr website with ASF Pelican action for PRs

on:
  pull_request:
    branches:
      - '**'

jobs:
  build-pelican:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Pelican Site
        uses: apache/infrastructure-actions/pelican@main
        with:
          gfm: 'false'
          version: '4.9.1'
          publish: 'false'
